#!/usr/bin/env python3
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
#
# mayhem/gen_schema_json.py -- generate GLTFSDK/Source/SchemaJson.h WITHOUT PowerShell.
#
# Upstream's own pre-build step (GLTFSDK/GenerateSchemaJsonHeader.ps1, wired via
# GLTFSDK/CMakeLists.txt's add_custom_command) shells out to `pwsh`/`powershell` to bake every
# GLTFSDK/schema/*.json file into a generated C++ header (SchemaJson::GLTF_SCHEMA_MAP, a
# filename -> raw-JSON-text map; the only symbol Schema.cpp actually reads from the generated
# file). The base image ships no PowerShell, and installing pwsh just to run a ~250-line
# text-templating script is unnecessary weight, so this script reproduces the one piece of
# generated code that matters -- byte for byte the same schema TEXT, just written by Python.
#
# NOT wired into upstream's CMake at all (upstream's add_custom_command still names the .ps1 via
# POWERSHELL_PATH). mayhem/build.sh instead calls this script directly, once per CMake build
# tree, AFTER cmake configure (so it knows the exact GeneratedFiles output path for that tree)
# and BEFORE `cmake --build`. Because the file we just wrote is newer than every schema/*.json
# input, Ninja/Make's own freshness check for the OUTPUT of upstream's add_custom_command sees
# nothing to do and skips invoking (a possibly not-even-found) PowerShell entirely -- no upstream
# file is edited to make this work.
import sys
from pathlib import Path

RAW_DELIM = "MAYHEMSCHEMA"


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen_schema_json.py <schema-dir> <output-header>", file=sys.stderr)
        return 1

    schema_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])
    out_path.parent.mkdir(parents=True, exist_ok=True)

    entries = []
    for f in sorted(schema_dir.glob("*.json")):
        content = f.read_text(encoding="utf-8").strip("\"'")
        if f")MAYHEMSCHEMA\"" in content or f"R\"MAYHEMSCHEMA(" in content:
            # Never expected for real glTF JSON schema text -- fail loudly rather than emit a
            # header that would silently truncate a schema at the raw-string delimiter.
            print(f"FATAL: {f} contains the raw-string delimiter {RAW_DELIM}", file=sys.stderr)
            return 1
        entries.append((f.name, content))

    if not entries:
        print(f"FATAL: no *.json schema files found under {schema_dir}", file=sys.stderr)
        return 1

    lines = [
        "// Copyright (c) Microsoft Corporation. All rights reserved.",
        "// Licensed under the MIT License.",
        "//",
        "// AUTOGENERATED by mayhem/gen_schema_json.py -- a PowerShell-free equivalent of",
        "// GenerateSchemaJsonHeader.ps1. Do not include in more than one translation unit",
        "// (defines a non-inline static member below).",
        "#pragma once",
        "#include <string>",
        "#include <unordered_map>",
        "",
        "namespace Microsoft {",
        "namespace glTF {",
        "",
        "class SchemaJson {",
        "public:",
        "    static const std::unordered_map<std::string, std::string> GLTF_SCHEMA_MAP;",
        "};",
        "",
        "const std::unordered_map<std::string, std::string> SchemaJson::GLTF_SCHEMA_MAP = {",
    ]
    for name, content in entries:
        lines.append('    { "%s", R"%s(%s)%s" },' % (name, RAW_DELIM, content, RAW_DELIM))
    lines += [
        "};",
        "",
        "} // namespace glTF",
        "} // namespace Microsoft",
        "",
    ]

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {out_path} ({len(entries)} schema entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
